# Generated by Django 6.0.7 on 2026-07-26 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='field_order',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('option_order', models.IntegerField(default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.field')),
            ],
        ),
    ]
