# Generated by Django 6.0.7 on 2026-07-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_field_created_at_field_field_order_fieldoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_value', models.CharField(max_length=255)),
                ('action', models.CharField(default='show', max_length=20)),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rules', to='myapp.field')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='myapp.field')),
            ],
        ),
    ]
