# Generated by Django 6.0.7 on 2026-07-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_conditionalrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.formversion')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.field')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.submission')),
            ],
        ),
    ]
