# Generated by Django 6.0.7 on 2026-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_submission_responsevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('multicheckbox', 'Multi Checkbox'), ('date', 'Date'), ('file', 'File Upload'), ('rating', 'Rating')], default='text', max_length=30),
        ),
    ]
