# Generated by Django 6.0.7 on 2026-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
