# Generated by Django 6.0.7 on 2026-08-06 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_form_fields_alter_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formversion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
