# Generated by Django 6.0.7 on 2026-08-06 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_formversion_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalrule',
            name='operator',
            field=models.CharField(default='equals', max_length=20),
        ),
        migrations.AlterField(
            model_name='formversion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
