# Generated by Django 6.0.7 on 2026-08-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_conditionalrule_operator_alter_formversion_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='min_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
