# Generated by Django 6.0.7 on 2026-08-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_field_max_length_field_max_value_field_min_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='form_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.field')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.submission')),
            ],
        ),
    ]
