# Generated by Django 6.0.7 on 2026-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_form_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='field',
            name='field_order',
        ),
        migrations.AddField(
            model_name='field',
            name='max_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='min_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
