# Generated by Django 6.0.7 on 2026-08-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_field_created_at_remove_field_field_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='max_date',
        ),
    ]
