# Generated by Django 6.0.7 on 2026-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_field_max_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='max_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
