# Generated by Django 6.0.7 on 2026-08-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_field_created_at_field_field_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='completion_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
