# Generated by Django 6.0.7 on 2026-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_submission_completion_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
