# Generated by Django 6.0.7 on 2026-08-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='retention_days',
            field=models.IntegerField(blank=True, default=365, null=True),
        ),
    ]
