# Generated by Django 6.0.7 on 2026-08-22 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_links', to='myapp.formversion')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_time_link', to='myapp.submission')),
            ],
        ),
    ]
