# Generated by Django 6.0.7 on 2026-08-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_onetimelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
