# Generated by Django 6.0.7 on 2026-08-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_onetimelink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='formversion',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
