# Generated by Django 6.0.7 on 2026-08-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_formversion_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='limit_one_response_per_email',
            field=models.BooleanField(default=False),
        ),
    ]
