# Generated by Django 6.0.7 on 2026-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_submission_respondent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='form',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
