# Generated by Django 5.2.1 on 2026-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_form_updated_at_form_scheduled_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='pattern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
